[workspace]
resolver = "2"
members = ["crates/colla", "crates/colla-wasm"]
default-members = ["crates/colla"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/link-duan/colla"

[workspace.dependencies]
colla = { path = "crates/colla", version = "0.1.0" }
