[package]
name = "colla-wasm"
version.workspace = true
edition.workspace = true
description = "Private WebAssembly bindings for colla-ot"
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
colla = { workspace = true, features = ["bindings"] }
js-sys = "0.3"
wasm-bindgen = "0.2"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]
